### PR TITLE
Improvement of specimen description

### PR DESCRIPTION
**Pull request by hackermd**
This PR introduces the following changes:

- Additional checks to ensure that `processing_type` and `processing_procedure` match
- Support for staining substances specified as text
- New `SpecimenProcessing` class to describe specimen processing

### CODE REVIEW

**Review by CPBridge — COMMENTED** [review]
Very unfamiliar with this part of the standard, but why does the `processing_type` even need to be passed if it's determined by the type of the `processing_procedure`?

**Comment by hackermd** [comment]
> Very unfamiliar with this part of the standard, but why does the `processing_type` even need to be passed if it's determined by the type of the `processing_procedure`?

You are right, it's not really required. I realized that having the two parameters (`processing_type` and `processing_procedure`) is error prone and therefore added checks to ensure that the arguments match. We could now deprecate `processing_type`. However, since it's currently the first parameter, we would break the API even if we would make it optional for the purpose of deprecation (since we would need to move the parameter). Thoughts?

**Comment by CPBridge** [comment]
Hmm, I'd be tempted to deprecate as gracefully as we can as we are still pre 1.0 but I defer to your judgement

**Comment by hackermd** [comment]
@CPBridge I deprecated the parameter and added a paragraph to the release notes (f8ddb989aa039c2944b2746eff46f4f84660eae7).

**Review by CPBridge — APPROVED** [review]
Looks good

**Pull request merged**
