### PR TITLE
Add factory method to construct UID from UUID

### PR DESCRIPTION
**Pull request by hackermd**

### CODE REVIEW

**Review by CPBridge — APPROVED** [review]
Looks ok to me. Curious about why the UID suffixes generated by pydicom are insufficient

**Comment by hackermd** [comment]
> Curious about why the UID suffixes generated by pydicom are insufficient

What do you mean?

**Comment by CPBridge** [comment]
What's lacking in the existing default constructor `UID()`, which uses pydicom to generate the suffix, such that this is useful?

**Comment by hackermd** [comment]
You cannot just pass a UUID string to the constructor of `UID`. The `generate_uid()` function will internally generate a UUID if `prefix=None`. However, if you already have a UUID and you want to use that (instead of a new, randomly generated one), you need to construct the UID yourself. That's what this factory method does.

**Comment by CPBridge** [comment]
I suppose... Not something that I'd ever thought of doing

**Comment by hackermd** [comment]
For example, when converting annotations that have been stored in a database into DICOM format, the existing data may be associated with identifiers in form of UUIDs. It may then be desirable to "re-use" these identifiers in the resulting DICOM objects.

**Pull request merged**
